SELECT X."U_BOT_HILOS" AS Hilo,
       COUNT(X."DocEntry") AS Cantidad
FROM B1H_INVERSIONES_PROD."@SGE_TRAN" X
WHERE X."U_BOT_SITUACION" = 0
  AND X."U_BOT_HILOS" != 0
GROUP BY X."U_BOT_HILOS"
ORDER BY X."U_BOT_HILOS" ASC;
